### PR TITLE
chore: Remove test references

### PR DESCRIPTION
**Pull request by nschonni**
Related to https://github.com/MicrosoftDocs/feedback/issues/824

### CODE REVIEW

**Comment by nschonni** [comment]
@divega do you know how to get this to stick given that these are generated?

**Comment by divega** [comment]
@nschonni I assume this could be accomplished by not pulling the packages where all the tests specs live (e.g. anything with Microsoft.EntityFrameworkCore*Specification* in its name. 

I assume there is a list of packages somewhere in this repo, but I haven't investigated and I am not super familiar with the tooling used for it. 

cc @mairaw and @dendeli-msft in case they know.

**Comment by mairaw** [comment]
There's an internal team that handles reference onboarding that can probably help with this question. I don't know well how reference docs work with published NuGet packages, because ours only works with assemblies for .NET.

We could also look into adding a filter similar to what I'm doing in PR #59. Removing the auto-generated content would be undone the next time we run CI.

@smitpatel are you going to be handling the updates for 3.0?

**Comment by smitpatel** [comment]
@mairaw - I can look into this too. I believe the issue happens because we also publish specification tests to NuGet for providers (and not for customers), and they are getting published. It would be somewhat difficult to filter them out as they live in same namespace as relevant product code they are testing.

**Comment by mairaw** [comment]
You can also filter some specific types.

**Comment by smitpatel** [comment]
Taken care in #63 
I have got doc team to remove publishing of Spec tests packages altogether.

**Pull request closed without merging**
