### PR TITLE
Fix to #942 - adding note about default command timeout

### PR DESCRIPTION
**Pull request by maumar**
i.e. that it is determined by provider. Also added links to provider specific documentation where the actual timeout values are specified.

### CODE REVIEW

**Comment by divega** [comment]
@maumar was this fixed in the EF Core source code?

**Comment by divega** [comment]
Apparently the EF Core codebase doesn't contain the change at https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.Relational/RelationalDatabaseFacadeExtensions.cs#L801, so this will be overwritten.

**Comment by smitpatel** [comment]
Tracked at https://github.com/aspnet/EntityFrameworkCore/issues/17503 in source.

**Comment by mairaw** [comment]
I'd also suggest that the API docs for this don't add this much info as a summary. Usually, summary is a short sentence and additional info should go into remarks. More on this at https://github.com/dotnet/dotnet-api-docs/wiki.

**Comment by smitpatel** [comment]
@mairaw - Thanks.

**Pull request closed without merging**
