### PR TITLE
typo cleanup

### PR DESCRIPTION
**Pull request by nschonni**
I did this as a large batch, but I can submit the commits separately if preferred

### CODE REVIEW

**Comment by divega** [comment]
@nschonni I really appreciate you effort here. So many typos! Unfortunately API documentation contents on this repo are automatically generated from the source code in the product repos, and the changes need to happen at the source. Please check the [readme file](https://github.com/aspnet/EntityFramework.ApiDocs/blob/master/README.md).

Cc @mairaw, @dendeli-msft, in case you are aware of any tooling that could merge these changes into the corresponding source.

**Comment by nschonni** [comment]
No problem, I thought it was like the dotnet-api-docs. I can see if I can backport them as well

**Comment by mairaw** [comment]
dotnet-api-docs is a bit of an exception when it comes to the .NET Core SDKs.
Perhaps @nschonni can run the same tool on the source?

**Comment by divega** [comment]
I am going to go ahead and close this PR here. Thanks for submitting the PRs to the product repos.

**Pull request closed without merging**
