### PR TITLE
Update EntityFrameworkQueryableExtensions.xml

### PR DESCRIPTION
**Pull request by luqq**
AsTracking() should return a query where the result set is tracked by the context

### CODE REVIEW

**Comment by divega** [comment]
@luqq good catch! This should be fixed in the XML comments in the product: https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore/EntityFrameworkQueryableExtensions.cs#L2568. 

@dend @mairaw How do we normally handle issues like this? Do we wait for the product to be fixed or do we also make changes directly in the API docs?

**Comment by dend** [comment]
@divega the recommendation here is to make sure that the change happens in the code comment (if that is where you import the comment from).

**Comment by divega** [comment]
@dend ok, it is now fixed now for all future versions. But it is still incorrect for all the current versions published in API Docs. Is there a way to fix it locally that we won't accidentally overwrite if we re-generate the API docs?

**Comment by divega** [comment]
@mairaw I believe it depends on whether the next time we regenerate the API docs from the XML comments we use a version of the binaries that contains the fix. 

If we need to do regenerate API docs to fix a bug on how it was generated (for example, to fix https://github.com/aspnet/EntityFramework.ApiDocs/issues/23), then we will still be using a version of the published bits that don't contain the fix and any edit to the API docs we do now will be lost.

An edit to API docs like this issue, would also apply retroactively to older versions of EF Core (or any library) that have been published and are not going to receive the fix.

Am I missing anything? Just asking in case there is a process for this kind of fixes.

**Comment by mairaw** [comment]
Makes sense. I think the scenario where you need to rerun with the same bits could cause the content to be overwritten.

@dend I don't know how this works for auto-generated content. If the summary is changed for example from one release to the next and you run CI, does the latest version win? Because you don't have the same field for each version, correct?

**Comment by dend** [comment]
@mairaw we will just pick up whatever is in the code. When you run our tool in "frameworks mode" (aka versioned), we will pick the latest summary as "de-facto" for APIs that span multiple versions.

**Comment by divega** [comment]
Closing since this is already fixed in the code and it is now stale. Thanks for reporting it @luqq.

**Pull request closed without merging**
